[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
baseUrlPath = ""
allowRunOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
